"use client";

import React, { useState, useRef, useCallback, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import useAuth from "@/utils/useAuth";
import { getAllCategories, getSubcategories as getSubcategoriesUtil } from "@/utils/categories";

import { API_URL } from '@/lib/api';

export default function AddProductPage() {
    const { token, user } = useAuth();
    const navigate = useNavigate();
    const [loading, setLoading] = useState(false);
    const [savingDraft, setSavingDraft] = useState(false);
    const [uploadingImages, setUploadingImages] = useState(false);
    const [uploadingVideo, setUploadingVideo] = useState(false);
    const [activeTab, setActiveTab] = useState("basic"); // basic, media, details, shipping, seo
    const [errors, setErrors] = useState({});
    const [touched, setTouched] = useState({});

    // Categories and subcategories from API
    const [categories, setCategories] = useState([]);
    const [subcategories, setSubcategories] = useState([]);
    const [loadingCategories, setLoadingCategories] = useState(false);
    const [loadingSubcategories, setLoadingSubcategories] = useState(false);

    // Uploaded files state
    const [uploadedImages, setUploadedImages] = useState([]);
    const [uploadedVideos, setUploadedVideos] = useState([]); // Changed to array for multiple videos

    // Drag states
    const [dragActiveImage, setDragActiveImage] = useState(false);
    const [dragActiveVideo, setDragActiveVideo] = useState(false);

    const imageInputRef = useRef(null);
    const videoInputRef = useRef(null);

    // Constants for limits
    const MAX_IMAGES = 7;
    const MAX_VIDEOS = 3;

    const [form, setForm] = useState({
        // Basic Info
        name: "",
        sku: "",
        price: "",
        compareAtPrice: "",
        brand: "",
        category: "",
        subcategory: "",
        countInStock: "",
        description: "",

        // Additional Details
        weight: "",
        weightUnit: "kg", // kg, g, lb, oz
        dimensions: {
            length: "",
            width: "",
            height: "",
            unit: "cm" // cm, m, in, ft
        },
        tags: [],
        tagInput: "",

        // Variants (for future)
        hasVariants: false,
        variants: [],

        // Shipping
        shippingRequired: true,
        shippingWeight: "",
        shippingClass: "standard", // standard, express, heavy
        freeShipping: false,

        // SEO
        metaTitle: "",
        metaDescription: "",
        slug: "",

        // Status
        status: "draft", // draft, active, archived
        featured: false
    });

    // Track if auto-generation has been done
    const autoGeneratedRef = useRef({ sku: false, slug: false, metaTitle: false });

    // Fetch categories from API on component mount
    useEffect(() => {
        const fetchCategories = async () => {
            setLoadingCategories(true);
            try {
                const res = await fetch(`${API_URL}/api/categories`);
                if (!res.ok) {
                    throw new Error(`HTTP error! status: ${res.status}`);
                }
                const data = await res.json();
                console.log('Categories API response:', data);
                if (data.success && Array.isArray(data.categories) && data.categories.length > 0) {
                    // Filter to ONLY show the 6 specified categories (remove any extras)
                    const allowedCategories = getAllCategories();
                    const filtered = data.categories.filter(cat => allowedCategories.includes(cat));
                    // Always ensure all 6 categories are present
                    const merged = [...new Set([...allowedCategories, ...filtered])]
                        .filter(cat => allowedCategories.includes(cat))
                        .sort();
                    setCategories(merged);
                } else {
                    // Fallback: Use default categories if API returns empty
                    console.warn('No categories found in database, using fallback categories');
                    setCategories(getAllCategories());
                }
            } catch (error) {
                console.error('Error fetching categories:', error);
                // Fallback: Use default categories on error
                setCategories(getAllCategories());
                setErrors(prev => ({ ...prev, categories: 'Using default categories (API unavailable)' }));
            } finally {
                setLoadingCategories(false);
            }
        };
        fetchCategories();
    }, []);

    // Fetch subcategories when category changes
    useEffect(() => {
        const fetchSubcategories = async () => {
            if (!form.category) {
                setSubcategories([]);
                return;
            }

            setLoadingSubcategories(true);
            try {
                const res = await fetch(`${API_URL}/api/categories/${encodeURIComponent(form.category)}/subcategories`);
                if (!res.ok) {
                    throw new Error(`HTTP error! status: ${res.status}`);
                }
                const data = await res.json();
                console.log('Subcategories API response:', data);
                if (data.success && Array.isArray(data.subcategories) && data.subcategories.length > 0) {
                    // Merge API subcategories with our known list (ensures full list)
                    const fallbackSubcats = getSubcategoriesUtil(form.category);
                    const merged = [...new Set([...fallbackSubcats, ...data.subcategories])].sort();
                    setSubcategories(merged);
                } else {
                    console.warn(`No subcategories found for category: ${form.category}, using fallback`);
                    // Fallback to utility function
                    const fallbackSubcats = getSubcategoriesUtil(form.category);
                    setSubcategories(fallbackSubcats);
                }
            } catch (error) {
                console.error('Error fetching subcategories:', error);
                // Fallback to utility function
                const fallbackSubcats = getSubcategoriesUtil(form.category);
                setSubcategories(fallbackSubcats);
            } finally {
                setLoadingSubcategories(false);
            }
        };
        fetchSubcategories();
    }, [form.category]);

    // Auto-generate SKU from product name (only once, when name is first entered)
    useEffect(() => {
        if (form.name && !autoGeneratedRef.current.sku && !touched.sku && !form.sku) {
            const sku = form.name
                .toUpperCase()
                .replace(/[^A-Z0-9]/g, '')
                .substring(0, 20)
                + '-' + Date.now().toString().slice(-6);
            setForm(prev => ({ ...prev, sku }));
            autoGeneratedRef.current.sku = true;
        }
    }, [form.name, form.sku, touched.sku]);

    // Auto-generate slug from product name (only once, when name is first entered)
    useEffect(() => {
        if (form.name && !autoGeneratedRef.current.slug && !touched.slug && !form.slug) {
            const slug = form.name
                .toLowerCase()
                .replace(/[^a-z0-9]+/g, '-')
                .replace(/(^-|-$)/g, '');
            setForm(prev => ({ ...prev, slug }));
            autoGeneratedRef.current.slug = true;
        }
    }, [form.name, form.slug, touched.slug]);

    // Auto-generate meta title from product name (only once, when name is first entered)
    useEffect(() => {
        if (form.name && !autoGeneratedRef.current.metaTitle && !touched.metaTitle && !form.metaTitle) {
            setForm(prev => ({ ...prev, metaTitle: form.name }));
            autoGeneratedRef.current.metaTitle = true;
        }
    }, [form.name, form.metaTitle, touched.metaTitle]);

    const handleChange = useCallback((e) => {
        const { name, value, type, checked } = e.target;

        setTouched(prev => ({ ...prev, [name]: true }));
        setErrors(prev => ({ ...prev, [name]: null }));

        setForm(prev => {
            const newForm = { ...prev };

            if (name.startsWith('dimensions.')) {
                const dimKey = name.split('.')[1];
                newForm.dimensions = {
                    ...prev.dimensions,
                    [dimKey]: value
                };
            } else if (type === 'checkbox') {
                newForm[name] = checked;
            } else {
                newForm[name] = value;

                // Reset subcategory if category changes
                if (name === "category") {
                    newForm.subcategory = "";
                }
            }

            return newForm;
        });
    }, []);

    const handleTagAdd = () => {
        if (form.tagInput.trim() && !form.tags.includes(form.tagInput.trim())) {
            setForm(prev => ({
                ...prev,
                tags: [...prev.tags, prev.tagInput.trim()],
                tagInput: ""
            }));
        }
    };

    const handleTagRemove = (tagToRemove) => {
        setForm(prev => ({
            ...prev,
            tags: prev.tags.filter(tag => tag !== tagToRemove)
        }));
    };

    const handleTagInputKeyPress = (e) => {
        if (e.key === 'Enter') {
            e.preventDefault();
            handleTagAdd();
        }
    };

    // Validation
    const validateForm = () => {
        const newErrors = {};

        if (!form.name.trim()) {
            newErrors.name = "Product name is required";
        } else if (form.name.trim().length < 3) {
            newErrors.name = "Product name must be at least 3 characters";
        }

        if (!form.price || parseFloat(form.price) <= 0) {
            newErrors.price = "Valid price is required";
        }

        if (form.compareAtPrice && parseFloat(form.compareAtPrice) <= parseFloat(form.price)) {
            newErrors.compareAtPrice = "Compare at price must be greater than regular price";
        }

        if (!form.category) {
            newErrors.category = "Category is required";
        }

        if (!form.subcategory) {
            newErrors.subcategory = "Subcategory is required";
        }

        if (!form.countInStock || parseInt(form.countInStock) < 0) {
            newErrors.countInStock = "Valid stock count is required";
        }

        if (!form.description.trim()) {
            newErrors.description = "Description is required";
        } else if (form.description.trim().length < 20) {
            newErrors.description = "Description must be at least 20 characters";
        }

        if (uploadedImages.length === 0) {
            newErrors.images = "At least one product image is required";
        }

        if (form.slug && !/^[a-z0-9-]+$/.test(form.slug)) {
            newErrors.slug = "Slug can only contain lowercase letters, numbers, and hyphens";
        }

        setErrors(newErrors);
        return Object.keys(newErrors).length === 0;
    };

    // Image upload handler - supports mobile and desktop
    const handleImageUpload = useCallback(async (files) => {
        if (!files || files.length === 0) return;

        const remainingSlots = MAX_IMAGES - uploadedImages.length;
        if (remainingSlots <= 0) {
            setErrors(prev => ({ ...prev, images: `Maximum ${MAX_IMAGES} images allowed` }));
            return;
        }

        const filesToUpload = Array.from(files).slice(0, remainingSlots);

        // Validate file types and sizes
        const validFiles = [];
        const invalidFiles = [];

        filesToUpload.forEach(file => {
            if (!file.type.startsWith('image/')) {
                invalidFiles.push(`${file.name} is not an image`);
            } else if (file.size > 10 * 1024 * 1024) { // 10MB limit
                invalidFiles.push(`${file.name} exceeds 10MB limit`);
            } else {
                validFiles.push(file);
            }
        });

        if (invalidFiles.length > 0) {
            setErrors(prev => ({ ...prev, images: invalidFiles.join(', ') }));
        }

        if (validFiles.length === 0) return;

        setUploadingImages(true);
        setErrors(prev => ({ ...prev, images: null }));

        try {
            const formData = new FormData();
            validFiles.forEach(file => formData.append('files', file));

            const res = await fetch(`${API_URL}/api/upload/product-images`, {
                method: 'POST',
                headers: { 'Authorization': `Bearer ${token}` },
                body: formData
            });

            const data = await res.json();

            if (data.files && data.files.length > 0) {
                setUploadedImages(prev => [...prev, ...data.files]);
            }

            if (data.errors && data.errors.length > 0) {
                setErrors(prev => ({ ...prev, images: `Some files failed: ${data.errors.map(e => e.error).join(', ')}` }));
            }
        } catch (error) {
            console.error('Upload error:', error);
            setErrors(prev => ({ ...prev, images: 'Failed to upload images. Please try again.' }));
        } finally {
            setUploadingImages(false);
        }
    }, [token, uploadedImages.length]);

    // Video upload handler - supports multiple videos and mobile/desktop
    const handleVideoUpload = useCallback(async (files) => {
        if (!files || files.length === 0) return;

        const fileArray = Array.isArray(files) ? files : [files];
        const remainingSlots = MAX_VIDEOS - uploadedVideos.length;

        if (remainingSlots <= 0) {
            setErrors(prev => ({ ...prev, video: `Maximum ${MAX_VIDEOS} videos allowed` }));
            return;
        }

        const filesToUpload = fileArray.slice(0, remainingSlots);

        // Validate file types and sizes
        const validFiles = [];
        const invalidFiles = [];

        filesToUpload.forEach(file => {
            if (!file.type.startsWith('video/')) {
                invalidFiles.push(`${file.name} is not a video`);
            } else if (file.size > 100 * 1024 * 1024) { // 100MB limit
                invalidFiles.push(`${file.name} exceeds 100MB limit`);
            } else {
                validFiles.push(file);
            }
        });

        if (invalidFiles.length > 0) {
            setErrors(prev => ({ ...prev, video: invalidFiles.join(', ') }));
        }

        if (validFiles.length === 0) return;

        setUploadingVideo(true);
        setErrors(prev => ({ ...prev, video: null }));

        try {
            // Upload videos one by one
            const uploadPromises = validFiles.map(async (file) => {
                const formData = new FormData();
                formData.append('file', file);

                const res = await fetch(`${API_URL}/api/upload/product-media`, {
                    method: 'POST',
                    headers: { 'Authorization': `Bearer ${token}` },
                    body: formData
                });

                const data = await res.json();
                return data.success ? data : null;
            });

            const results = await Promise.all(uploadPromises);
            const successfulUploads = results.filter(r => r !== null);

            if (successfulUploads.length > 0) {
                setUploadedVideos(prev => [...prev, ...successfulUploads]);
            }

            if (successfulUploads.length < validFiles.length) {
                setErrors(prev => ({ ...prev, video: `Some videos failed to upload` }));
            }
        } catch (error) {
            console.error('Upload error:', error);
            setErrors(prev => ({ ...prev, video: 'Failed to upload videos. Please try again.' }));
        } finally {
            setUploadingVideo(false);
        }
    }, [token, uploadedVideos.length]);

    // Remove image
    const removeImage = (index) => {
        setUploadedImages(prev => prev.filter((_, i) => i !== index));
    };

    // Reorder images
    const moveImage = (index, direction) => {
        const newImages = [...uploadedImages];
        const newIndex = direction === 'up' ? index - 1 : index + 1;
        if (newIndex >= 0 && newIndex < newImages.length) {
            [newImages[index], newImages[newIndex]] = [newImages[newIndex], newImages[index]];
            setUploadedImages(newImages);
        }
    };

    // Remove video
    const removeVideo = (index) => {
        setUploadedVideos(prev => prev.filter((_, i) => i !== index));
    };

    // Drag handlers for images
    const handleDragImage = (e) => {
        e.preventDefault();
        e.stopPropagation();
        if (e.type === "dragenter" || e.type === "dragover") {
            setDragActiveImage(true);
        } else if (e.type === "dragleave") {
            setDragActiveImage(false);
        }
    };

    const handleDropImage = (e) => {
        e.preventDefault();
        e.stopPropagation();
        setDragActiveImage(false);

        const files = e.dataTransfer.files;
        const imageFiles = Array.from(files).filter(f => f.type.startsWith('image/'));
        if (imageFiles.length > 0) {
            handleImageUpload(imageFiles);
        }
    };

    // Drag handlers for video
    const handleDragVideo = (e) => {
        e.preventDefault();
        e.stopPropagation();
        if (e.type === "dragenter" || e.type === "dragover") {
            setDragActiveVideo(true);
        } else if (e.type === "dragleave") {
            setDragActiveVideo(false);
        }
    };

    const handleDropVideo = (e) => {
        e.preventDefault();
        e.stopPropagation();
        setDragActiveVideo(false);

        const files = e.dataTransfer.files;
        const videoFiles = Array.from(files).filter(f => f.type.startsWith('video/'));
        if (videoFiles.length > 0) {
            handleVideoUpload(videoFiles);
        }
    };

    const handleSaveDraft = async () => {
        setSavingDraft(true);
        try {
            const productData = {
                ...form,
                status: 'draft',
                image: uploadedImages[0]?.url || '',
                images: uploadedImages.map(img => img.url),
                video_url: uploadedVideos.length > 0 ? uploadedVideos[0].url : null, // Primary video
                videos: uploadedVideos.map(vid => vid.url), // All videos
                tags: form.tags.join(',')
            };

            const res = await fetch(`${API_URL}/api/products`, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    Authorization: `Bearer ${token}`
                },
                body: JSON.stringify(productData)
            });

            if (!res.ok) {
                const error = await res.json();
                throw new Error(error.message || "Failed to save draft");
            }

            alert("Draft saved successfully!");
            navigate("/seller/inventory");
        } catch (error) {
            console.error(error);
            alert("Error saving draft: " + error.message);
        } finally {
            setSavingDraft(false);
        }
    };

    const handleSubmit = async (e) => {
        e.preventDefault();

        if (!validateForm()) {
            setActiveTab("basic"); // Go to first tab with errors
            return;
        }

        setLoading(true);

        try {
            const productData = {
                ...form,
                status: 'active',
                image: uploadedImages[0]?.url || '',
                images: uploadedImages.map(img => img.url),
                video_url: uploadedVideos.length > 0 ? uploadedVideos[0].url : null, // Primary video
                videos: uploadedVideos.map(vid => vid.url), // All videos
                tags: form.tags.join(','),
                compareAtPrice: form.compareAtPrice || null,
                weight: form.weight ? `${form.weight} ${form.weightUnit}` : null,
                dimensions: form.dimensions.length ?
                    `${form.dimensions.length}x${form.dimensions.width}x${form.dimensions.height} ${form.dimensions.unit}` :
                    null
            };

            const res = await fetch(`${API_URL}/api/products`, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    Authorization: `Bearer ${token}`
                },
                body: JSON.stringify(productData)
            });

            if (!res.ok) {
                const error = await res.json();
                throw new Error(error.message || "Failed to create product");
            }

            const product = await res.json();
            navigate("/seller/inventory");
        } catch (error) {
            console.error(error);
            alert("Error saving product: " + error.message);
        } finally {
            setLoading(false);
        }
    };

    const formatFileSize = (bytes) => {
        if (bytes < 1024) return bytes + ' B';
        if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB';
        return (bytes / (1024 * 1024)).toFixed(1) + ' MB';
    };

    const tabs = [
        { id: "basic", label: "Basic Info", icon: "fa-info-circle" },
        { id: "media", label: "Media", icon: "fa-images" },
        { id: "details", label: "Details", icon: "fa-list" },
        { id: "shipping", label: "Shipping", icon: "fa-truck" },
        { id: "seo", label: "SEO", icon: "fa-search" }
    ];

    return (
        <div className="max-w-5xl mx-auto space-y-6">
            <div className="flex items-center justify-between">
                <button onClick={() => navigate("/seller/inventory")} className="flex items-center text-gray-500 hover:text-gray-900">
                    <i className="fa-solid fa-arrow-left w-5 h-5 mr-1"></i> Back to Inventory
                </button>
                <div className="flex gap-2">
                    <button
                        type="button"
                        onClick={handleSaveDraft}
                        disabled={savingDraft}
                        className="px-4 py-2 border border-gray-300 rounded-md text-gray-700 hover:bg-gray-50 disabled:opacity-50"
                    >
                        {savingDraft ? "Saving..." : "Save Draft"}
                    </button>
                </div>
            </div>

            <div className="bg-white shadow-sm rounded-lg border border-gray-200">
                <div className="p-6 border-b border-gray-200">
                    <h1 className="text-2xl font-bold font-playfair text-[#232f3e]">Add New Product</h1>
                    <p className="text-sm text-gray-500 mt-1">Fill in the product details below</p>
                </div>

                {/* Tabs */}
                <div className="border-b border-gray-200 bg-gray-50">
                    <div className="flex overflow-x-auto scrollbar-hide">
                        {tabs.map(tab => (
                            <button
                                key={tab.id}
                                type="button"
                                onClick={() => setActiveTab(tab.id)}
                                className={`flex items-center gap-2 px-6 py-4 border-b-2 transition-all whitespace-nowrap ${activeTab === tab.id
                                    ? 'border-orange-500 text-orange-600 font-semibold bg-white'
                                    : 'border-transparent text-gray-500 hover:text-gray-700 hover:bg-gray-100'
                                    }`}
                            >
                                <i className={`fa-solid ${tab.icon} text-sm`}></i>
                                <span className="text-sm">{tab.label}</span>
                            </button>
                        ))}
                    </div>
                </div>

                <form onSubmit={handleSubmit} className="p-6">
                    {/* Basic Info Tab */}
                    {activeTab === "basic" && (
                        <div className="space-y-6">
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">
                                    Product Name <span className="text-red-500">*</span>
                                </label>
                                <input
                                    type="text"
                                    name="name"
                                    required
                                    value={form.name}
                                    onChange={handleChange}
                                    onBlur={() => setTouched(prev => ({ ...prev, name: true }))}
                                    className={`mt-1 block w-full border rounded-lg shadow-sm py-2.5 px-4 text-sm transition-colors focus:ring-2 focus:ring-orange-500 focus:border-orange-500 outline-none ${errors.name ? 'border-red-300 bg-red-50' : 'border-gray-300 bg-white hover:border-gray-400'
                                        }`}
                                    placeholder="Enter product name"
                                />
                                {errors.name && <p className="mt-1.5 text-sm text-red-600 flex items-center gap-1">
                                    <i className="fa-solid fa-circle-exclamation text-xs"></i>
                                    {errors.name}
                                </p>}
                            </div>

                            <div className="grid grid-cols-2 gap-6">
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-1">
                                        SKU <span className="text-red-500">*</span>
                                    </label>
                                    <input
                                        type="text"
                                        name="sku"
                                        required
                                        value={form.sku}
                                        onChange={handleChange}
                                        onFocus={() => setTouched(prev => ({ ...prev, sku: true }))}
                                        className="mt-1 block w-full border border-gray-300 rounded-lg shadow-sm py-2.5 px-4 text-sm transition-colors focus:ring-2 focus:ring-orange-500 focus:border-orange-500 outline-none bg-white hover:border-gray-400"
                                        placeholder="Auto-generated"
                                    />
                                    <p className="mt-1 text-xs text-gray-500">Auto-generated from product name</p>
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-1">
                                        Brand <span className="text-red-500">*</span>
                                    </label>
                                    <input
                                        type="text"
                                        name="brand"
                                        required
                                        value={form.brand}
                                        onChange={handleChange}
                                        className={`mt-1 block w-full border rounded-lg shadow-sm py-2.5 px-4 text-sm transition-colors focus:ring-2 focus:ring-orange-500 focus:border-orange-500 outline-none ${errors.brand ? 'border-red-300 bg-red-50' : 'border-gray-300 bg-white hover:border-gray-400'
                                            }`}
                                        placeholder="Enter brand name"
                                    />
                                    {errors.brand && <p className="mt-1.5 text-sm text-red-600">{errors.brand}</p>}
                                </div>
                            </div>

                            <div className="grid grid-cols-2 gap-6">
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-1">
                                        Price (₹) <span className="text-red-500">*</span>
                                    </label>
                                    <div className="relative">
                                        <span className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500">₹</span>
                                        <input
                                            type="number"
                                            name="price"
                                            required
                                            min="0"
                                            step="0.01"
                                            value={form.price}
                                            onChange={handleChange}
                                            onBlur={() => setTouched(prev => ({ ...prev, price: true }))}
                                            className={`mt-1 block w-full border rounded-lg shadow-sm py-2.5 pl-7 pr-4 text-sm transition-colors focus:ring-2 focus:ring-orange-500 focus:border-orange-500 outline-none ${errors.price ? 'border-red-300 bg-red-50' : 'border-gray-300 bg-white hover:border-gray-400'
                                                }`}
                                            placeholder="0.00"
                                        />
                                    </div>
                                    {errors.price && <p className="mt-1.5 text-sm text-red-600 flex items-center gap-1">
                                        <i className="fa-solid fa-circle-exclamation text-xs"></i>
                                        {errors.price}
                                    </p>}
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-1">
                                        Compare at Price
                                        <span className="ml-2 text-xs text-gray-400 font-normal">(optional)</span>
                                    </label>
                                    <div className="relative">
                                        <span className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500">₹</span>
                                        <input
                                            type="number"
                                            name="compareAtPrice"
                                            min="0"
                                            step="0.01"
                                            value={form.compareAtPrice}
                                            onChange={handleChange}
                                            onBlur={() => setTouched(prev => ({ ...prev, compareAtPrice: true }))}
                                            className={`mt-1 block w-full border rounded-lg shadow-sm py-2.5 pl-7 pr-4 text-sm transition-colors focus:ring-2 focus:ring-orange-500 focus:border-orange-500 outline-none ${errors.compareAtPrice ? 'border-red-300 bg-red-50' : 'border-gray-300 bg-white hover:border-gray-400'
                                                }`}
                                            placeholder="0.00"
                                        />
                                    </div>
                                    {errors.compareAtPrice && <p className="mt-1.5 text-sm text-red-600 flex items-center gap-1">
                                        <i className="fa-solid fa-circle-exclamation text-xs"></i>
                                        {errors.compareAtPrice}
                                    </p>}
                                    <p className="mt-1.5 text-xs text-gray-500 flex items-center gap-1">
                                        <i className="fa-solid fa-info-circle text-xs"></i>
                                        Show customers the original price for discounts
                                    </p>
                                </div>
                            </div>

                            <div className="grid grid-cols-2 gap-6">
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-1">
                                        Category <span className="text-red-500">*</span>
                                    </label>
                                    <select
                                        name="category"
                                        required
                                        value={form.category}
                                        onChange={handleChange}
                                        onBlur={() => setTouched(prev => ({ ...prev, category: true }))}
                                        disabled={loadingCategories}
                                        className={`mt-1 block w-full border rounded-lg shadow-sm py-2.5 px-4 text-sm transition-colors focus:ring-2 focus:ring-orange-500 focus:border-orange-500 outline-none cursor-pointer disabled:bg-gray-100 disabled:cursor-not-allowed ${errors.category ? 'border-red-300 bg-red-50' : 'border-gray-300 bg-white hover:border-gray-400'
                                            }`}
                                    >
                                        <option value="">
                                            {loadingCategories ? 'Loading categories...' : 'Select Category'}
                                        </option>
                                        {categories.map(cat => (
                                            <option key={cat} value={cat}>{cat}</option>
                                        ))}
                                    </select>
                                    {errors.category && <p className="mt-1.5 text-sm text-red-600 flex items-center gap-1">
                                        <i className="fa-solid fa-circle-exclamation text-xs"></i>
                                        {errors.category}
                                    </p>}
                                    {loadingCategories && (
                                        <p className="mt-1.5 text-xs text-gray-500 flex items-center gap-1">
                                            <i className="fa-solid fa-spinner fa-spin text-xs"></i>
                                            Loading categories...
                                        </p>
                                    )}
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-1">
                                        Subcategory <span className="text-red-500">*</span>
                                    </label>
                                    <select
                                        name="subcategory"
                                        required
                                        value={form.subcategory}
                                        onChange={handleChange}
                                        disabled={!form.category || loadingSubcategories}
                                        onBlur={() => setTouched(prev => ({ ...prev, subcategory: true }))}
                                        className={`mt-1 block w-full border rounded-lg shadow-sm py-2.5 px-4 text-sm transition-colors focus:ring-2 focus:ring-orange-500 focus:border-orange-500 outline-none cursor-pointer disabled:bg-gray-100 disabled:cursor-not-allowed ${errors.subcategory ? 'border-red-300 bg-red-50' : 'border-gray-300 bg-white hover:border-gray-400'
                                            }`}
                                    >
                                        <option value="">
                                            {!form.category
                                                ? 'Select category first'
                                                : loadingSubcategories
                                                    ? 'Loading subcategories...'
                                                    : subcategories.length === 0
                                                        ? 'No subcategories available'
                                                        : 'Select Subcategory'
                                            }
                                        </option>
                                        {subcategories.map(sub => (
                                            <option key={sub} value={sub}>{sub}</option>
                                        ))}
                                    </select>
                                    {errors.subcategory && <p className="mt-1.5 text-sm text-red-600 flex items-center gap-1">
                                        <i className="fa-solid fa-circle-exclamation text-xs"></i>
                                        {errors.subcategory}
                                    </p>}
                                    {loadingSubcategories && form.category && (
                                        <p className="mt-1.5 text-xs text-gray-500 flex items-center gap-1">
                                            <i className="fa-solid fa-spinner fa-spin text-xs"></i>
                                            Loading subcategories...
                                        </p>
                                    )}
                                </div>
                            </div>

                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">
                                    Stock Count <span className="text-red-500">*</span>
                                </label>
                                <input
                                    type="number"
                                    name="countInStock"
                                    required
                                    min="0"
                                    value={form.countInStock}
                                    onChange={handleChange}
                                    onBlur={() => setTouched(prev => ({ ...prev, countInStock: true }))}
                                    className={`mt-1 block w-full border rounded-lg shadow-sm py-2.5 px-4 text-sm transition-colors focus:ring-2 focus:ring-orange-500 focus:border-orange-500 outline-none ${errors.countInStock ? 'border-red-300 bg-red-50' : 'border-gray-300 bg-white hover:border-gray-400'
                                        }`}
                                    placeholder="0"
                                />
                                {errors.countInStock && <p className="mt-1.5 text-sm text-red-600 flex items-center gap-1">
                                    <i className="fa-solid fa-circle-exclamation text-xs"></i>
                                    {errors.countInStock}
                                </p>}
                            </div>

                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">
                                    Description <span className="text-red-500">*</span>
                                </label>
                                <textarea
                                    name="description"
                                    rows={6}
                                    required
                                    value={form.description}
                                    onChange={handleChange}
                                    onBlur={() => setTouched(prev => ({ ...prev, description: true }))}
                                    className={`mt-1 block w-full border rounded-lg shadow-sm py-2.5 px-4 text-sm transition-colors focus:ring-2 focus:ring-orange-500 focus:border-orange-500 outline-none resize-y ${errors.description ? 'border-red-300 bg-red-50' : 'border-gray-300 bg-white hover:border-gray-400'
                                        }`}
                                    placeholder="Describe your product in detail... (minimum 20 characters)"
                                />
                                {errors.description && <p className="mt-1.5 text-sm text-red-600 flex items-center gap-1">
                                    <i className="fa-solid fa-circle-exclamation text-xs"></i>
                                    {errors.description}
                                </p>}
                                <p className={`mt-1.5 text-xs flex items-center gap-1 ${form.description.length < 20 ? 'text-orange-600' : 'text-gray-500'
                                    }`}>
                                    <i className={`fa-solid ${form.description.length < 20 ? 'fa-exclamation-triangle' : 'fa-check-circle'} text-xs`}></i>
                                    {form.description.length} / 20 characters minimum
                                </p>
                            </div>
                        </div>
                    )}

                    {/* Media Tab */}
                    {activeTab === "media" && (
                        <div className="space-y-6">
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-2">
                                    <span className="flex items-center gap-2">
                                        <i className="fa-solid fa-image text-gray-500"></i>
                                        Product Images <span className="text-red-500">*</span>
                                        <span className="text-gray-400 font-normal">(up to {MAX_IMAGES}, max 10MB each)</span>
                                    </span>
                                </label>

                                <div
                                    onDragEnter={handleDragImage}
                                    onDragLeave={handleDragImage}
                                    onDragOver={handleDragImage}
                                    onDrop={handleDropImage}
                                    onClick={() => {
                                        if (uploadedImages.length < MAX_IMAGES && !uploadingImages) {
                                            imageInputRef.current?.click();
                                        }
                                    }}
                                    className={`border-2 border-dashed rounded-lg p-8 text-center transition-colors ${uploadedImages.length >= MAX_IMAGES
                                        ? 'opacity-50 cursor-not-allowed border-gray-200'
                                        : 'cursor-pointer border-gray-300 hover:border-gray-400'
                                        } ${dragActiveImage
                                            ? 'border-orange-500 bg-orange-50'
                                            : ''
                                        } ${errors.images ? 'border-red-300' : ''
                                        }`}
                                >
                                    <input
                                        ref={imageInputRef}
                                        type="file"
                                        accept="image/*"
                                        multiple
                                        className="hidden"
                                        onChange={(e) => {
                                            if (e.target.files && e.target.files.length > 0) {
                                                handleImageUpload(e.target.files);
                                            }
                                            // Reset input to allow selecting same file again or adding more files
                                            e.target.value = '';
                                        }}
                                        disabled={uploadedImages.length >= MAX_IMAGES || uploadingImages}
                                    />

                                    {uploadingImages ? (
                                        <div className="flex flex-col items-center">
                                            <i className="fa-solid fa-spinner fa-spin text-3xl text-orange-500"></i>
                                            <p className="mt-2 text-sm text-gray-500">Uploading...</p>
                                        </div>
                                    ) : uploadedImages.length >= MAX_IMAGES ? (
                                        <div className="flex flex-col items-center">
                                            <i className="fa-solid fa-check-circle text-3xl text-green-500"></i>
                                            <p className="mt-2 text-sm text-gray-600 font-medium">Maximum images reached ({MAX_IMAGES})</p>
                                            <p className="text-xs text-gray-400 mt-1">Remove images to add more</p>
                                        </div>
                                    ) : (
                                        <>
                                            <i className="fa-solid fa-cloud-arrow-up text-4xl text-gray-400 mx-auto"></i>
                                            <p className="mt-3 text-sm text-gray-600">
                                                <span className="hidden sm:inline">Drag & drop images here, or </span>
                                                <span className="text-orange-600 font-medium">click to browse</span>
                                            </p>
                                            <p className="text-xs text-gray-400 mt-1">PNG, JPG, GIF, WebP up to 10MB each</p>
                                            <p className="text-xs text-gray-500 mt-2 flex items-center justify-center gap-1">
                                                <i className="fa-solid fa-mobile-screen-button"></i>
                                                <span>Works on mobile and desktop</span>
                                            </p>
                                            {uploadedImages.length > 0 && (
                                                <p className="text-xs text-orange-600 mt-2 font-medium">
                                                    You can select multiple files at once (Ctrl+Click or Cmd+Click)
                                                </p>
                                            )}
                                        </>
                                    )}
                                </div>
                                {errors.images && <p className="mt-2 text-sm text-red-600">{errors.images}</p>}

                                {uploadedImages.length > 0 && (
                                    <div className="mt-4">
                                        <p className="text-xs text-gray-500 mb-2 flex items-center gap-1">
                                            <i className="fa-solid fa-images"></i>
                                            {uploadedImages.length} / {MAX_IMAGES} images uploaded
                                        </p>
                                        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-7 gap-3">
                                            {uploadedImages.map((img, index) => (
                                                <div key={index} className="relative group">
                                                    <div className="aspect-square rounded-lg overflow-hidden border-2 border-gray-200 bg-gray-100">
                                                        <img
                                                            src={img.url}
                                                            alt={`Product ${index + 1}`}
                                                            className="w-full h-full object-cover"
                                                            loading="lazy"
                                                        />
                                                    </div>
                                                    {index === 0 && (
                                                        <span className="absolute top-1 left-1 bg-orange-500 text-white text-xs px-2 py-1 rounded shadow-sm">
                                                            Main
                                                        </span>
                                                    )}
                                                    <div className="absolute top-1 right-1 flex gap-1 opacity-0 group-hover:opacity-100 group-focus-within:opacity-100 transition-opacity">
                                                        {index > 0 && (
                                                            <button
                                                                type="button"
                                                                onClick={() => moveImage(index, 'up')}
                                                                className="bg-blue-500 text-white rounded-full p-1.5 w-7 h-7 flex items-center justify-center shadow-md hover:bg-blue-600 transition-colors"
                                                                title="Move up"
                                                                aria-label="Move image up"
                                                            >
                                                                <i className="fa-solid fa-arrow-up text-xs"></i>
                                                            </button>
                                                        )}
                                                        {index < uploadedImages.length - 1 && (
                                                            <button
                                                                type="button"
                                                                onClick={() => moveImage(index, 'down')}
                                                                className="bg-blue-500 text-white rounded-full p-1.5 w-7 h-7 flex items-center justify-center shadow-md hover:bg-blue-600 transition-colors"
                                                                title="Move down"
                                                                aria-label="Move image down"
                                                            >
                                                                <i className="fa-solid fa-arrow-down text-xs"></i>
                                                            </button>
                                                        )}
                                                        <button
                                                            type="button"
                                                            onClick={() => removeImage(index)}
                                                            className="bg-red-500 text-white rounded-full p-1.5 w-7 h-7 flex items-center justify-center shadow-md hover:bg-red-600 transition-colors"
                                                            title="Remove"
                                                            aria-label="Remove image"
                                                        >
                                                            <i className="fa-solid fa-xmark text-xs"></i>
                                                        </button>
                                                    </div>
                                                </div>
                                            ))}
                                        </div>
                                    </div>
                                )}
                            </div>

                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-2">
                                    <span className="flex items-center gap-2">
                                        <i className="fa-solid fa-video text-gray-500"></i>
                                        Product Videos
                                        <span className="text-gray-400 font-normal">(optional, up to {MAX_VIDEOS}, max 100MB each)</span>
                                    </span>
                                </label>

                                {uploadedVideos.length < MAX_VIDEOS && (
                                    <div
                                        onDragEnter={handleDragVideo}
                                        onDragLeave={handleDragVideo}
                                        onDragOver={handleDragVideo}
                                        onDrop={handleDropVideo}
                                        onClick={() => videoInputRef.current?.click()}
                                        className={`border-2 border-dashed rounded-lg p-8 text-center cursor-pointer transition-colors ${dragActiveVideo
                                            ? 'border-purple-500 bg-purple-50'
                                            : 'border-gray-300 hover:border-gray-400'
                                            } ${uploadedVideos.length >= MAX_VIDEOS ? 'opacity-50 cursor-not-allowed' : ''} ${errors.video ? 'border-red-300' : ''
                                            }`}
                                    >
                                        <input
                                            ref={videoInputRef}
                                            type="file"
                                            accept="video/*"
                                            multiple
                                            className="hidden"
                                            onChange={(e) => {
                                                if (e.target.files && e.target.files.length > 0) {
                                                    handleVideoUpload(e.target.files);
                                                }
                                                // Reset input to allow selecting same file again
                                                e.target.value = '';
                                            }}
                                            disabled={uploadedVideos.length >= MAX_VIDEOS}
                                        />

                                        {uploadingVideo ? (
                                            <div className="flex flex-col items-center">
                                                <i className="fa-solid fa-spinner fa-spin text-3xl text-purple-500"></i>
                                                <p className="mt-2 text-sm text-gray-500">Uploading videos...</p>
                                            </div>
                                        ) : (
                                            <>
                                                <i className="fa-solid fa-video text-4xl text-gray-400 mx-auto"></i>
                                                <p className="mt-3 text-sm text-gray-600">
                                                    <span className="hidden sm:inline">Drag & drop videos here, or </span>
                                                    <span className="text-purple-600 font-medium">click to browse</span>
                                                </p>
                                                <p className="text-xs text-gray-400 mt-1">MP4, WebM, MOV up to 100MB each</p>
                                                <p className="text-xs text-gray-500 mt-2">
                                                    {uploadedVideos.length} / {MAX_VIDEOS} videos uploaded
                                                </p>
                                                <p className="text-xs text-gray-500 mt-1 flex items-center justify-center gap-1">
                                                    <i className="fa-solid fa-mobile-screen-button"></i>
                                                    <span>Works on mobile and desktop</span>
                                                </p>
                                            </>
                                        )}
                                    </div>
                                )}

                                {errors.video && <p className="mt-2 text-sm text-red-600 flex items-center gap-1">
                                    <i className="fa-solid fa-circle-exclamation text-xs"></i>
                                    {errors.video}
                                </p>}

                                {uploadedVideos.length > 0 && (
                                    <div className="mt-4 space-y-3">
                                        {uploadedVideos.map((video, index) => (
                                            <div key={index} className="border rounded-lg p-4 bg-gray-50">
                                                <div className="flex items-center justify-between mb-3">
                                                    <div className="flex items-center gap-3">
                                                        <i className="fa-solid fa-circle-check text-xl text-green-500"></i>
                                                        <div>
                                                            <p className="text-sm font-medium text-gray-700">
                                                                Video {index + 1}
                                                                {index === 0 && <span className="ml-2 text-xs bg-purple-100 text-purple-700 px-2 py-0.5 rounded">Primary</span>}
                                                            </p>
                                                            <p className="text-xs text-gray-500">{formatFileSize(video.size || 0)}</p>
                                                        </div>
                                                    </div>
                                                    <button
                                                        type="button"
                                                        onClick={() => removeVideo(index)}
                                                        className="text-red-500 hover:text-red-700 p-1"
                                                        title="Remove video"
                                                    >
                                                        <i className="fa-solid fa-xmark text-xl"></i>
                                                    </button>
                                                </div>
                                                <video
                                                    src={video.url}
                                                    controls
                                                    className="w-full max-h-64 rounded"
                                                    preload="metadata"
                                                    playsInline
                                                />
                                            </div>
                                        ))}
                                    </div>
                                )}
                            </div>
                        </div>
                    )}

                    {/* Details Tab */}
                    {activeTab === "details" && (
                        <div className="space-y-6">
                            <div className="grid grid-cols-2 gap-6">
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-1">Weight</label>
                                    <div className="flex gap-2">
                                        <input
                                            type="number"
                                            name="weight"
                                            min="0"
                                            step="0.01"
                                            value={form.weight}
                                            onChange={handleChange}
                                            className="flex-1 border border-gray-300 rounded-lg shadow-sm py-2.5 px-4 text-sm transition-colors focus:ring-2 focus:ring-orange-500 focus:border-orange-500 outline-none bg-white hover:border-gray-400"
                                            placeholder="0.00"
                                        />
                                        <select
                                            name="weightUnit"
                                            value={form.weightUnit}
                                            onChange={handleChange}
                                            className="border border-gray-300 rounded-lg shadow-sm py-2.5 px-4 text-sm transition-colors focus:ring-2 focus:ring-orange-500 focus:border-orange-500 outline-none bg-white hover:border-gray-400 cursor-pointer"
                                        >
                                            <option value="kg">kg</option>
                                            <option value="g">g</option>
                                            <option value="lb">lb</option>
                                            <option value="oz">oz</option>
                                        </select>
                                    </div>
                                </div>
                            </div>

                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">Dimensions</label>
                                <div className="grid grid-cols-4 gap-2">
                                    <input
                                        type="number"
                                        name="dimensions.length"
                                        min="0"
                                        step="0.01"
                                        value={form.dimensions.length}
                                        onChange={handleChange}
                                        className="border border-gray-300 rounded-lg shadow-sm py-2.5 px-3 text-sm transition-colors focus:ring-2 focus:ring-orange-500 focus:border-orange-500 outline-none bg-white hover:border-gray-400"
                                        placeholder="Length"
                                    />
                                    <input
                                        type="number"
                                        name="dimensions.width"
                                        min="0"
                                        step="0.01"
                                        value={form.dimensions.width}
                                        onChange={handleChange}
                                        className="border border-gray-300 rounded-lg shadow-sm py-2.5 px-3 text-sm transition-colors focus:ring-2 focus:ring-orange-500 focus:border-orange-500 outline-none bg-white hover:border-gray-400"
                                        placeholder="Width"
                                    />
                                    <input
                                        type="number"
                                        name="dimensions.height"
                                        min="0"
                                        step="0.01"
                                        value={form.dimensions.height}
                                        onChange={handleChange}
                                        className="border border-gray-300 rounded-lg shadow-sm py-2.5 px-3 text-sm transition-colors focus:ring-2 focus:ring-orange-500 focus:border-orange-500 outline-none bg-white hover:border-gray-400"
                                        placeholder="Height"
                                    />
                                    <select
                                        name="dimensions.unit"
                                        value={form.dimensions.unit}
                                        onChange={handleChange}
                                        className="border border-gray-300 rounded-lg shadow-sm py-2.5 px-3 text-sm transition-colors focus:ring-2 focus:ring-orange-500 focus:border-orange-500 outline-none bg-white hover:border-gray-400 cursor-pointer"
                                    >
                                        <option value="cm">cm</option>
                                        <option value="m">m</option>
                                        <option value="in">in</option>
                                        <option value="ft">ft</option>
                                    </select>
                                </div>
                            </div>

                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">Tags</label>
                                <div className="flex gap-2 mb-2">
                                    <input
                                        type="text"
                                        value={form.tagInput}
                                        onChange={(e) => setForm(prev => ({ ...prev, tagInput: e.target.value }))}
                                        onKeyPress={handleTagInputKeyPress}
                                        className="flex-1 border border-gray-300 rounded-lg shadow-sm py-2.5 px-4 text-sm transition-colors focus:ring-2 focus:ring-orange-500 focus:border-orange-500 outline-none bg-white hover:border-gray-400"
                                        placeholder="Add a tag and press Enter"
                                    />
                                    <button
                                        type="button"
                                        onClick={handleTagAdd}
                                        className="px-4 py-2.5 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 transition-colors font-medium text-sm"
                                    >
                                        <i className="fa-solid fa-plus mr-1"></i>
                                        Add
                                    </button>
                                </div>
                                {form.tags.length > 0 && (
                                    <div className="flex flex-wrap gap-2">
                                        {form.tags.map((tag, index) => (
                                            <span
                                                key={index}
                                                className="inline-flex items-center gap-1 px-3 py-1 bg-orange-100 text-orange-800 rounded-full text-sm"
                                            >
                                                {tag}
                                                <button
                                                    type="button"
                                                    onClick={() => handleTagRemove(tag)}
                                                    className="hover:text-orange-900"
                                                >
                                                    <i className="fa-solid fa-xmark text-xs"></i>
                                                </button>
                                            </span>
                                        ))}
                                    </div>
                                )}
                            </div>

                            <div className="flex items-center gap-2 p-3 bg-gray-50 rounded-lg">
                                <input
                                    type="checkbox"
                                    name="featured"
                                    checked={form.featured}
                                    onChange={handleChange}
                                    className="w-4 h-4 rounded border-gray-300 text-orange-500 focus:ring-2 focus:ring-orange-500 cursor-pointer"
                                />
                                <label className="text-sm font-medium text-gray-700 cursor-pointer">Feature this product</label>
                                <span className="ml-auto text-xs text-gray-500">
                                    <i className="fa-solid fa-star text-orange-500 mr-1"></i>
                                    Featured products appear prominently
                                </span>
                            </div>
                        </div>
                    )}

                    {/* Shipping Tab */}
                    {activeTab === "shipping" && (
                        <div className="space-y-6">
                            <div className="flex items-center gap-2 p-3 bg-gray-50 rounded-lg">
                                <input
                                    type="checkbox"
                                    name="shippingRequired"
                                    checked={form.shippingRequired}
                                    onChange={handleChange}
                                    className="w-4 h-4 rounded border-gray-300 text-orange-500 focus:ring-2 focus:ring-orange-500 cursor-pointer"
                                />
                                <label className="text-sm font-medium text-gray-700 cursor-pointer">This product requires shipping</label>
                            </div>

                            {form.shippingRequired && (
                                <>
                                    <div className="grid grid-cols-2 gap-6">
                                        <div>
                                            <label className="block text-sm font-medium text-gray-700 mb-1">Shipping Weight</label>
                                            <input
                                                type="number"
                                                name="shippingWeight"
                                                min="0"
                                                step="0.01"
                                                value={form.shippingWeight}
                                                onChange={handleChange}
                                                className="mt-1 block w-full border border-gray-300 rounded-lg shadow-sm py-2.5 px-4 text-sm transition-colors focus:ring-2 focus:ring-orange-500 focus:border-orange-500 outline-none bg-white hover:border-gray-400"
                                                placeholder="0.00"
                                            />
                                        </div>
                                        <div>
                                            <label className="block text-sm font-medium text-gray-700 mb-1">Shipping Class</label>
                                            <select
                                                name="shippingClass"
                                                value={form.shippingClass}
                                                onChange={handleChange}
                                                className="mt-1 block w-full border border-gray-300 rounded-lg shadow-sm py-2.5 px-4 text-sm transition-colors focus:ring-2 focus:ring-orange-500 focus:border-orange-500 outline-none bg-white hover:border-gray-400 cursor-pointer"
                                            >
                                                <option value="standard">Standard</option>
                                                <option value="express">Express</option>
                                                <option value="heavy">Heavy/Bulky</option>
                                            </select>
                                        </div>
                                    </div>

                                    <div className="flex items-center gap-2 p-3 bg-gray-50 rounded-lg">
                                        <input
                                            type="checkbox"
                                            name="freeShipping"
                                            checked={form.freeShipping}
                                            onChange={handleChange}
                                            className="w-4 h-4 rounded border-gray-300 text-orange-500 focus:ring-2 focus:ring-orange-500 cursor-pointer"
                                        />
                                        <label className="text-sm font-medium text-gray-700 cursor-pointer">Offer free shipping for this product</label>
                                    </div>
                                </>
                            )}
                        </div>
                    )}

                    {/* SEO Tab */}
                    {activeTab === "seo" && (
                        <div className="space-y-6">
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">URL Slug</label>
                                <div className="flex items-center gap-2">
                                    <span className="text-sm text-gray-500 whitespace-nowrap">yourstore.com/products/</span>
                                    <input
                                        type="text"
                                        name="slug"
                                        value={form.slug}
                                        onChange={handleChange}
                                        onFocus={() => setTouched(prev => ({ ...prev, slug: true }))}
                                        className={`flex-1 border rounded-lg shadow-sm py-2.5 px-4 text-sm transition-colors focus:ring-2 focus:ring-orange-500 focus:border-orange-500 outline-none ${errors.slug ? 'border-red-300 bg-red-50' : 'border-gray-300 bg-white hover:border-gray-400'
                                            }`}
                                        placeholder="product-url-slug"
                                    />
                                </div>
                                {errors.slug && <p className="mt-1.5 text-sm text-red-600 flex items-center gap-1">
                                    <i className="fa-solid fa-circle-exclamation text-xs"></i>
                                    {errors.slug}
                                </p>}
                                <p className="mt-1.5 text-xs text-gray-500 flex items-center gap-1">
                                    <i className="fa-solid fa-info-circle text-xs"></i>
                                    Auto-generated from product name
                                </p>
                            </div>

                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">Meta Title</label>
                                <input
                                    type="text"
                                    name="metaTitle"
                                    value={form.metaTitle}
                                    onChange={handleChange}
                                    maxLength={60}
                                    className="mt-1 block w-full border border-gray-300 rounded-lg shadow-sm py-2.5 px-4 text-sm transition-colors focus:ring-2 focus:ring-orange-500 focus:border-orange-500 outline-none bg-white hover:border-gray-400"
                                    placeholder="SEO title for search engines"
                                />
                                <p className={`mt-1.5 text-xs flex items-center gap-1 ${form.metaTitle.length > 60 ? 'text-red-600' : form.metaTitle.length > 50 ? 'text-orange-600' : 'text-gray-500'
                                    }`}>
                                    <i className={`fa-solid ${form.metaTitle.length > 60 ? 'fa-exclamation-triangle' : 'fa-check-circle'} text-xs`}></i>
                                    {form.metaTitle.length}/60 characters
                                </p>
                            </div>

                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">Meta Description</label>
                                <textarea
                                    name="metaDescription"
                                    rows={3}
                                    value={form.metaDescription}
                                    onChange={handleChange}
                                    maxLength={160}
                                    className="mt-1 block w-full border border-gray-300 rounded-lg shadow-sm py-2.5 px-4 text-sm transition-colors focus:ring-2 focus:ring-orange-500 focus:border-orange-500 outline-none resize-y bg-white hover:border-gray-400"
                                    placeholder="Brief description for search engines"
                                />
                                <p className={`mt-1.5 text-xs flex items-center gap-1 ${form.metaDescription.length > 160 ? 'text-red-600' : form.metaDescription.length > 150 ? 'text-orange-600' : 'text-gray-500'
                                    }`}>
                                    <i className={`fa-solid ${form.metaDescription.length > 160 ? 'fa-exclamation-triangle' : 'fa-check-circle'} text-xs`}></i>
                                    {form.metaDescription.length}/160 characters
                                </p>
                            </div>
                        </div>
                    )}

                    {/* Form Actions */}
                    <div className="pt-6 mt-8 border-t border-gray-200 bg-gray-50 -mx-6 -mb-6 px-6 py-4">
                        <div className="flex justify-between items-center">
                            <div className="flex items-center gap-3">
                                <span className="text-sm text-gray-500">Quick Navigation:</span>
                                <div className="flex gap-1.5">
                                    {tabs.map((tab, index) => (
                                        <button
                                            key={tab.id}
                                            type="button"
                                            onClick={() => setActiveTab(tab.id)}
                                            className={`px-3 py-1.5 text-xs rounded-lg transition-colors ${activeTab === tab.id
                                                ? 'bg-orange-500 text-white shadow-sm'
                                                : 'bg-white text-gray-600 hover:bg-gray-100 border border-gray-300'
                                                }`}
                                        >
                                            {index + 1}
                                        </button>
                                    ))}
                                </div>
                            </div>
                            <div className="flex gap-3">
                                <button
                                    type="button"
                                    onClick={() => navigate("/seller/inventory")}
                                    className="px-5 py-2.5 border border-gray-300 rounded-lg text-gray-700 hover:bg-white transition-colors font-medium text-sm"
                                >
                                    Cancel
                                </button>
                                <button
                                    type="button"
                                    onClick={handleSaveDraft}
                                    disabled={savingDraft}
                                    className="px-5 py-2.5 border border-gray-300 rounded-lg text-gray-700 hover:bg-white transition-colors font-medium text-sm disabled:opacity-50"
                                >
                                    {savingDraft ? (
                                        <>
                                            <i className="fa-solid fa-spinner fa-spin mr-2"></i>
                                            Saving...
                                        </>
                                    ) : (
                                        <>
                                            <i className="fa-solid fa-save mr-2"></i>
                                            Save Draft
                                        </>
                                    )}
                                </button>
                                <button
                                    type="submit"
                                    disabled={loading}
                                    className="flex items-center px-6 py-2.5 border border-transparent rounded-lg shadow-sm text-sm font-semibold text-white bg-[#febd69] hover:bg-[#d97534] transition-all disabled:opacity-50 disabled:cursor-not-allowed hover:shadow-md"
                                >
                                    {loading ? (
                                        <>
                                            <i className="fa-solid fa-spinner fa-spin mr-2"></i>
                                            Publishing...
                                        </>
                                    ) : (
                                        <>
                                            <i className="fa-solid fa-rocket mr-2"></i>
                                            Publish Product
                                        </>
                                    )}
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    );
}
